import DeleteSKUFromPortfolio from '../StoreSkuTable/ActionForDeleteFromPortfolio';

const columns = [
  {
    field: '_id',
    headerName: 'Store ID',
    align: 'center',
    type: 'number',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'store_name',
    headerName: 'Store Name',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'store_rating',
    type: 'number',
    headerName: 'Store Rate',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'product',
    type: 'number',
    headerName: 'No of SKUs',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'store_soh',
    type: 'number',
    headerName: 'SOH',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'store_offer_price',
    headerName: 'Average Selling Price',
    align: 'center',
    headerAlign: 'center',
    width: 190,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'estimated_value',
    type: 'number',
    headerName: 'Estimated Value',
    align: 'center',
    headerAlign: 'center',
    width: 190,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'percentage',
    headerName: 'Selection Percentage',
    align: 'center',
    headerAlign: 'center',
    width: 190,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'actions',
    headerName: 'Actions',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <DeleteSKUFromPortfolio remove={false} row={row} />,
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
  },
];

export default columns;
