import MPLogo from 'components/common/MPLogo';
import SkuColumn from 'components/common/TableColumns/SkuColumn';

const columns = [
  {
    field: 'id',
    hide: true,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku',
    headerName: 'SKU',
    align: 'center',
    headerAlign: 'center',
    width: 200,
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
    renderCell: ({ row }) => <SkuColumn row={row} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'marketplace',
    headerName: 'Marketplace',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <MPLogo marketplace={row?.sku_marketplace} />,
    width: 110,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'category',
    type: 'number',
    headerName: 'Category',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'brands',
    type: 'number',
    headerName: 'Brand',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'stores',
    type: 'number',
    headerName: 'Stores',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'status',
    type: 'number',
    headerName: 'SKU Status',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'eMkt',
    type: 'number',
    headerName: 'E Marketplace Cap',
    align: 'center',
    headerAlign: 'center',
    width: 140,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'trade',
    type: 'number',
    headerName: 'Trade Volume',
    align: 'center',
    headerAlign: 'center',
    width: 140,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'chg',
    type: 'number',
    headerName: 'Chg 24H',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'asp',
    type: 'number',
    headerName: 'ASP',
    align: 'center',
    headerAlign: 'center',
    width: 50,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'mCap',
    type: 'number',
    headerName: 'Vol(24h)/MCap',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'stock',
    type: 'number',
    headerName: 'Opp to stock',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'fullfilment',
    type: 'number',
    headerName: 'Opp to Fulfilment',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'oppOther',
    type: 'number',
    headerName: 'E Opp to Other Platform Fulfilment',
    align: 'center',
    headerAlign: 'center',
    width: 250,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'max_investment',
    type: 'number',
    headerName: 'Max Investment',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'min_investment',
    type: 'number',
    headerName: 'Min Investment',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'est24',
    type: 'number',
    headerName: 'Sales volume L 24 H',
    align: 'center',
    headerAlign: 'center',
    width: 200,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'demand',
    type: 'number',
    headerName: 'Demand %',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'supply',
    type: 'number',
    headerName: 'Supply %',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'enr',
    type: 'number',
    headerName: 'ENR',
    align: 'center',
    headerAlign: 'center',
    width: 50,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'doh',
    headerName: 'DOH',
    align: 'center',
    headerAlign: 'center',
    width: 85,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'EQTI',
    headerName: 'EQTI',
    align: 'center',
    headerAlign: 'center',
    width: 85,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'em',
    type: 'number',
    headerName: 'EM',
    align: 'center',
    headerAlign: 'center',
    width: 50,
    headerClassName: 'super-app-theme--header',
  },
];

export default columns;
