import MPLogo from 'components/common/MPLogo';
import FulfillmentColumn from 'components/common/TableColumns/FulfillmentColumn';
import LiveColumn from 'components/common/TableColumns/LiveColumn';
import SkuColumn from 'components/common/TableColumns/SkuColumn';
import TagsColumn from 'components/common/TableColumns/TagsColumn';
import DeleteSKUFromPortfolio from '../StoreSkuTable/ActionForDeleteFromPortfolio';

const columns = [
  {
    field: '_id',
    hide: true,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku',
    headerName: 'SKU',
    align: 'center',
    headerAlign: 'center',
    width: 180,
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
    renderCell: ({ row }) => <SkuColumn row={row} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'marketplace',
    headerName: 'Marketplace',
    align: 'center',
    headerAlign: 'center',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
    renderCell: (params) => <MPLogo marketplace={params.row?.sku_marketplace} />,
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  
  {
    field: 'category_en',
    type: 'number',
    hide: true,
    headerName: 'Category',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'brand_en',
    type: 'number',
    hide: true,
    headerName: 'Brand',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'estimated_SOH',
    type: 'number',
    headerName: 'Estimated SOH',
    align: 'center',
    hide: true,
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'number_of_sellers',
    type: 'number',
    headerName: 'Stores',
    align: 'center',
    hide: true,
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'sku_rate',
    type: 'number',
    hide: true,
    headerName: 'Rate',
    align: 'center',
    headerAlign: 'center',
    width: 70,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'sku_rank',
    type: 'number',
    hide: true,
    headerName: 'Rank',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'fulfillment',
    renderCell: ({ row }) => <FulfillmentColumn row={row} />,
    type: 'number',
    headerName: 'Fulfillment Type',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'is_live',
    type: 'boolean',
    headerName: 'SKU Status',
    align: 'center',
    headerAlign: 'center',
    width: 110,
    headerClassName: 'super-app-theme--header',
    renderCell: ({ row }) => <LiveColumn row={row} />,
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'store_sale_price',
    type: 'number',
    headerName: 'Store Sale Price',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'current_price',
    type: 'number',
    headerName: 'BuyBox Sale Price',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'price_change',
    type: 'number',
    headerName: 'Chg 24H',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'mxPrice',
    type: 'number',
    headerName: 'Max Offer Price',
    hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'minPrice',
    type: 'number',
    hide: true,
    headerName: 'Min Offer Price',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'eof',
    type: 'number',
    hide: true,
    headerName: 'E Opp To Fulfillment',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'eos',
    headerName: 'E Opp To Stock',
    align: 'center',
    hide: true,
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'trade_value',
    type: 'number',
    hide: true,
    headerName: 'Trade Volume',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'tags',
    headerName: 'Tags',
    hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 80,
    renderCell: ({ row }) => <TagsColumn row={row} />,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'average_selling_price',
    type: 'number',
    headerName: 'ASP',
    align: 'center',
    headerAlign: 'center',
    width: 60,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'volume_to_market_cap_ratio',
    type: 'number',
    hide: true,
    headerName: 'Vol (24h) / MCap',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },

  {
    field: 'doh',
    type: 'number',
    hide: true,
    headerName: 'DOH',
    align: 'center',
    headerAlign: 'center',
    width: 60,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'enr',
    type: 'number',
    hide: true,
    headerName: 'ENR',
    align: 'center',
    headerAlign: 'center',
    width: 60,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'max_investment',
    type: 'number',
    headerName: 'Max Investment',
    align: 'center',
    headerAlign: 'center',
    width: 140,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'min_investment',
    type: 'number',
    headerName: 'Min Investment',
    align: 'center',
    headerAlign: 'center',
    width: 140,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'EQTI',
    type: 'number',
    hide: true,
    headerName: 'EQTI',
    align: 'center',
    headerAlign: 'center',
    width: 60,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'em',
    type: 'number',
    hide: true,
    headerName: 'EM',
    align: 'center',
    headerAlign: 'center',
    width: 50,
    hide: true,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'sold_24_hours',
    type: 'number',
    hide: true,
    headerName: 'Sales volume L 24 H',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'est_market_cap',
    type: 'number',
    hide: true,
    headerName: 'E Marketplace cap',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'eoas',
    type: 'number',
    hide: true,
    headerName: 'E Opp to Other Platform Fulfillment',
    align: 'center',
    headerAlign: 'center',
    width: 250,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'demand_percentage',
    type: 'number',
    hide: true,
    headerName: 'Demand',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'supply_percentage',
    type: 'number',
    hide: true,
    headerName: 'Supply',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'actions',
    headerName: 'Actions',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <DeleteSKUFromPortfolio remove={false} row={row} />,
    width: 140,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: true,
    disableColumnMenu: true,
  },
];

export default columns;
