import MPLogo from 'components/common/MPLogo';
import SkuColumn from 'components/common/TableColumns/SkuColumn';
import DeleteSKUFromPortfolio from '../StoreSkuTable/ActionForDeleteFromPortfolio';

const columns = [
  {
    field: 'id',
    hide: true,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku',
    headerName: 'SKU',
    align: 'center',
    headerAlign: 'center',
    width: 180,
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
    renderCell: ({ row }) => <SkuColumn row={row} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'marketplace',
    headerName: 'Marketplace',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <MPLogo marketplace={row?.sku_marketplace} />,
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'category',
    type: 'number',
    hide: true,
    headerName: 'Category',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'brands',
    type: 'number',
    hide: true,
    headerName: 'Brand',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'lbsp',
    type: 'number',
    headerName: 'Buybox Sale Price',
    hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 180,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'price_change',
    type: 'number',
    hide: true,
    headerName: 'Chg 24h',
    align: 'center',
    headerAlign: 'center',
    width: 135,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'estimated_SOH',
    type: 'number',
    hide: true,
    headerName: 'Estimated SOH',
    align: 'center',
    headerAlign: 'center',
    width: 135,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'sold_24_hours',
    type: 'number',
    headerName: 'Sales volume L 24 H',
    hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 235,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'status',
    type: 'number',
    headerName: 'SKU Status',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'fullfilment',
    type: 'number',
    headerName: 'Opp to Fulfilment',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'eos',
    type: 'number',
    headerName: 'Opp to Stock',
    align: 'center',
    headerAlign: 'center',
    width: 180,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'demand',
    type: 'number',
    headerName: 'Demand %',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'supply',
    type: 'number',
    headerName: 'Supply %',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'doh',
    headerName: 'DOH',
    align: 'center',
    headerAlign: 'center',
    width: 85,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'oppOther',
    type: 'number',
    headerName: 'E Opp to Other Platform Fulfilment',
    align: 'center',
    headerAlign: 'center',
    width: 250,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    disableColumnMenu: true,
  },
  {
    field: 'actions',
    headerName: 'Actions',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <DeleteSKUFromPortfolio remove={false} row={row} />,
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
  },
];

export default columns;
