import React from 'react';

const alldata = [
  {
    id:234243,
    Sku: 'N35997789A',
    SkuCompany: 'Asos Ridley High',
    SkuName: 'Tommme Tippee',
    BuyboxPrice: 23,
    MarketPlaceImg: '../assets/images/svg/noon-saudi.svg',
    Stores: 34,
    Rate: 43,
    Rank: 54,
    FulfilmentType: 'EG 230',
    SkuStatus: -4.4,
    Chg24H: 34,
    MaxOfferPrice: 43,
    MinOfferPrice: 345,
    EoppToFulfilment: 45,
    EoppToStock: 23,
    priceGraphs: '../assets/images/dashboardgreenchart.png',
    MaxInvestment: 234,
    MinInvestment: 34,
    ENR: 34,
    DOH: 'EG 230',
    EQTI: 4.4,
    EM: 34,
    TopRanked: 435,
    TopCategories: 345,
    TopBrands: 56,
    LiveSku: 53,
    LiveSkuSice: 345,
    NotLiveSkus: 354,
    FulfilmentByStores: 345,
  },
  {
    id:234243,
    Sku: 'N35997789A',
    SkuCompany: 'Asos Ridley High',
    SkuName: 'Tommme Tippee',
    BuyboxPrice: 23,
    MarketPlaceImg: '../assets/images/svg/noon-saudi.svg',
    Stores: 34,
    Rate: 43,
    Rank: 54,
    FulfilmentType: 'EG 230',
    SkuStatus: -4.4,
    Chg24H: 34,
    MaxOfferPrice: 43,
    MinOfferPrice: 345,
    EoppToFulfilment: 45,
    EoppToStock: 23,
    priceGraphs: '../assets/images/dashboardgreenchart.png',
    MaxInvestment: 234,
    MinInvestment: 34,
    ENR: 34,
    DOH: 'EG 230',
    EQTI: 4.4,
    EM: 34,
    TopRanked: 435,
    TopCategories: 345,
    TopBrands: 56,
    LiveSku: 53,
    LiveSkuSice: 345,
    NotLiveSkus: 354,
    FulfilmentByStores: 345,
  },
  {
    id:234243,
    Sku: 'N35997789A',
    SkuCompany: 'Asos Ridley High',
    SkuName: 'Tommme Tippee',
    BuyboxPrice: 23,
    MarketPlaceImg: '../assets/images/svg/noon-saudi.svg',
    Stores: 34,
    Rate: 43,
    Rank: 54,
    FulfilmentType: 'EG 230',
    SkuStatus: -4.4,
    Chg24H: 34,
    MaxOfferPrice: 43,
    MinOfferPrice: 345,
    EoppToFulfilment: 45,
    EoppToStock: 23,
    priceGraphs: '../assets/images/dashboardgreenchart.png',
    MaxInvestment: 234,
    MinInvestment: 34,
    ENR: 34,
    DOH: 'EG 230',
    EQTI: 4.4,
    EM: 34,
    TopRanked: 435,
    TopCategories: 345,
    TopBrands: 56,
    LiveSku: 53,
    LiveSkuSice: 345,
    NotLiveSkus: 354,
    FulfilmentByStores: 345,
  },
  {
    id:234243,
    Sku: 'N35997789A',
    SkuCompany: 'Asos Ridley High',
    SkuName: 'Tommme Tippee',
    BuyboxPrice: 23,
    MarketPlaceImg: '../assets/images/svg/noon-saudi.svg',
    Stores: 34,
    Rate: 43,
    Rank: 54,
    FulfilmentType: 'EG 230',
    SkuStatus: -4.4,
    Chg24H: 34,
    MaxOfferPrice: 43,
    MinOfferPrice: 345,
    EoppToFulfilment: 45,
    EoppToStock: 23,
    priceGraphs: '../assets/images/dashboardgreenchart.png',
    MaxInvestment: 234,
    MinInvestment: 34,
    ENR: 34,
    DOH: 'EG 230',
    EQTI: 4.4,
    EM: 34,
    TopRanked: 435,
    TopCategories: 345,
    TopBrands: 56,
    LiveSku: 53,
    LiveSkuSice: 345,
    NotLiveSkus: 354,
    FulfilmentByStores: 345,
  },
  {
    id:234243,
    Sku: 'N35997789A',
    SkuCompany: 'Asos Ridley High',
    SkuName: 'Tommme Tippee',
    BuyboxPrice: 23,
    MarketPlaceImg: '../assets/images/svg/noon-saudi.svg',
    Stores: 34,
    Rate: 43,
    Rank: 54,
    FulfilmentType: 'EG 230',
    SkuStatus: -4.4,
    Chg24H: 34,
    MaxOfferPrice: 43,
    MinOfferPrice: 345,
    EoppToFulfilment: 45,
    EoppToStock: 23,
    priceGraphs: '../assets/images/dashboardgreenchart.png',
    MaxInvestment: 234,
    MinInvestment: 34,
    ENR: 34,
    DOH: 'EG 230',
    EQTI: 4.4,
    EM: 34,
    TopRanked: 435,
    TopCategories: 345,
    TopBrands: 56,
    LiveSku: 53,
    LiveSkuSice: 345,
    NotLiveSkus: 354,
    FulfilmentByStores: 345,
  },
  {
    id:234243,
    Sku: 'N35997789A',
    SkuCompany: 'Asos Ridley High',
    SkuName: 'Tommme Tippee',
    BuyboxPrice: 23,
    MarketPlaceImg: '../assets/images/svg/noon-saudi.svg',
    Stores: 34,
    Rate: 43,
    Rank: 54,
    FulfilmentType: 'EG 230',
    SkuStatus: -4.4,
    Chg24H: 34,
    MaxOfferPrice: 43,
    MinOfferPrice: 345,
    EoppToFulfilment: 45,
    EoppToStock: 23,
    priceGraphs: '../assets/images/dashboardgreenchart.png',
    MaxInvestment: 234,
    MinInvestment: 34,
    ENR: 34,
    DOH: 'EG 230',
    EQTI: 4.4,
    EM: 34,
    TopRanked: 435,
    TopCategories: 345,
    TopBrands: 56,
    LiveSku: 53,
    LiveSkuSice: 345,
    NotLiveSkus: 354,
    FulfilmentByStores: 345,
  },
];

export default alldata;
