import { Typography } from '@mui/material';
import MPLogo from 'components/common/MPLogo';
import SkuColumn from 'components/common/TableColumns/SkuColumn';
import DeleteSKUFromPortfolio from '../StoreSkuTable/ActionForDeleteFromPortfolio';
import RatioTab from '../TopGainersTable/RatioTab';

const columns = [
  {
    field: 'id',
    hide: true,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku',
    headerName: 'SKU',
    align: 'center',
    headerAlign: 'center',
    width: 180,
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
    renderCell: ({ row }) => <SkuColumn row={row} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku_marketplace',
    headerName: 'Marketplace',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <MPLogo marketplace={row?.sku_marketplace} />,
    width: 100,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'category_en',
    type: 'number',
    hide: true,
    headerName: 'Category',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'brand_en',
    type: 'number',
    hide: true,
    headerName: 'Brand',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'current_price',
    type: 'number',
    headerName: 'BuyBox Sale Price',
     hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 135,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'price_change',
    type: 'number',
    headerName: 'Chg 24H',
     hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
    renderCell: ({ row }) => (
      <Typography
        sx={{
          color: row?.price_change > 0 ? 'success.main' : 'error.main',
        }}
      >
        {row?.price_change} %
      </Typography>
    ),
  },
  {
    field: 'max',
    type: 'number',
    headerName: 'Max Offer Price',
    align: 'center',
    hide: true,
    headerAlign: 'center',
    width: 140,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'min',
    type: 'number',
    headerName: 'Min Offer Price',
    align: 'center',
    headerAlign: 'center',
    hide: true,
    width: 140,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'status',
    type: 'number',
    headerName: 'SKU Status',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'max_investment',
    hide: true,
    type: 'number',
    headerName: 'Max Investment',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'min_investment',
    hide: true,
    type: 'number',
    headerName: 'Min Investment',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'est',
    type: 'number',
    headerName: 'Estimated SOH',
    hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'est24',
    type: 'number',
    headerName: 'Sales volume L 24 H',
    align: 'center',
    headerAlign: 'center',
    width: 200,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'demand',
    type: 'number',
    hide: true,
    headerName: 'Demand %',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'supply',
    type: 'number',
    hide: true,
    headerName: 'Supply %',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'ratio',
    headerName: 'Ratio',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <RatioTab row={row} />,
    width: 130,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
  },
  {
    field: 'actions',
    headerName: 'Actions',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <DeleteSKUFromPortfolio remove={false} row={row} />,
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
  },
];

export default columns;
