import { Stack } from '@mui/material';
import MPLogo from 'components/common/MPLogo';
import SkuColumn from 'components/common/TableColumns/SkuColumn';
import ActiveStatus from './ActiveStatus';
import DeleteSKU from './DeleteSKU';
import TranAndWatch from './transactionAndWatchList';
import UpdateAlert from './UpdateAlert';

const columns = [
  {
    field: 'id',
    hide: true,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku',
    headerName: 'SKU',
    align: 'center',
    headerAlign: 'center',
    width: 250,
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
    renderCell: ({ row }) => <SkuColumn row={row} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku_marketplace',
    headerName: 'Marketplace',
    align: 'center',
    headerAlign: 'center',
    renderCell: ({ row }) => <MPLogo marketplace={row?.sku_marketplace} />,
    width: 120,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'category_en',
    type: 'string',
    headerName: 'Category',
    hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'brand_en',
    type: 'string',
    hide: true,
    headerName: 'Brand',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'store',
    type: 'number',
    headerName: 'Stores',
    align: 'center',
    headerAlign: 'center',
    width: 135,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'sku_rate',
    type: 'number',
    hide: true,
    headerName: 'Rate',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'sku_rank',
    type: 'number',
    headerName: 'Rank',
    hide: true,
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'fulfillment_type',
    type: 'number',
    headerName: 'Fulfillment Type',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'is_live',
    type: 'boolean',
    headerName: 'SKU Status',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'price',
    type: 'number',
    headerName: 'Buy box Sale Price',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  {
    field: 'stock',
    type: 'number',
    headerName: 'Estimated SOH',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
  },
  // {
  //     field: 'active',
  //     type: 'boolean',
  //     headerName: 'Active Status',
  //     align: 'center',
  //     headerAlign: 'center',
  //     width: 120,
  //     renderCell: ({ row }) => <ActiveStatus row={row} />,
  //     headerClassName: 'super-app-theme--header',
  // },
  // {
  //     field: 'edit',
  //     type: 'boolean',
  //     headerName: 'Edit',
  //     align: 'center',
  //     headerAlign: 'center',
  //     width: 50,
  //     renderCell: ({ row }) => <UpdateAlert row={row} />,
  //     headerClassName: 'super-app-theme--header',
  // },
  {
    field: 'Actions',
    headerName: 'Actions',
    align: 'center',
    headerAlign: 'center',
    width: 210,
    renderCell: ({ row }) => {
      return (
        <Stack direction="row" justifyContent="center" alignItems="center">
          <TranAndWatch row={row} />
          <ActiveStatus row={row} />
          <UpdateAlert row={row} />
          <DeleteSKU row={row} />
        </Stack>
      );
    },
    sortable: true,
    filterable: true,
    disableColumnMenu: true,
    headerClassName: 'super-app-theme--header',
  },
];

export default columns;
