export const articles = [
  {
    id: 1,
    title: 'Terms and Conditions',
    icon: 'mdi:script-text-key-outline',
    questions: ['What is SKU Markets Policies?', 'The store name & products general information?'],
    qty: 2,
  },
  {
    id: 2,
    title: 'Managing Your Account',
    icon: 'material-symbols:settings-account-box-outline',
    questions: ['How I Sign In?', 'How to set my account Settings to use SKU Markets?'],
    qty: 2,
  },
  {
    id: 3,
    title: 'Top Ranked SKUs Management',
    icon: 'eos-icons:content-lifecycle-management',
    questions: [
      'What is Marketplaces page for?',
      'What is Watchlists page for?',
      'What is Alerts page for?',
    ],
    qty: 3,
  },
  {
    id: 4,
    title: 'Portfolio Management',
    icon: 'carbon:id-management',
    questions: [
      'What is Portfolio page for?',
      'How can I manage my SKUs on SKU Markets for other existing platforms?',
      'What is Watchlists page for?',
      'What is Alerts page for?',
      'How to bulk upload up to unlimited SKUs to my alerts?',
      'How to bulk upload up to unlimited SKUs to my portfolio?',
    ],
    qty: 6,
  },
  {
    id: 5,
    title: 'Selling on SKU Markets',
    icon: 'ep:sell',
    questions: [
      'What is SKU Markets page for?',
      'How can I add my SKUs on SKU Markets selling platform?',
      'What is SKU Markets Growth page for?',
      'What is SKU Markets Competitors page for?',
    ],
    qty: 4,
  },
  {
    id: 6,
    title: 'Request New stock',
    icon: 'healthicons:rdt-result-out-stock-outline',
    questions: [
      'What is SKU View page for?',
      'How do I request for quotation?',
      'What is Sellerboard page for?',
      'What is SKU Markets Growth page for?',
      'What is SKU Markets Competitors page for?',
    ],
    qty: 5,
  },
  {
    id: 7,
    title: 'Sellerboard',
    icon: 'carbon:dashboard-reference',
    questions: [
      'What is Sellerboard page for?',
      'How I use sellerboard to manage my orders and requests?',
      'How I use sellerboard to manage my shipments?',
      'How I use sellerboard to manage my invoices?',
      'How I use sellerboard to manage my payments?',
      'How I use sellerboard to withdraw my completed orders?',
      'How I use sellerboard to withdraw my rejected orders?',
    ],
    qty: 7,
  },
  {
    id: 8,
    title: 'Manage your orders',
    icon: 'fluent-mdl2:activate-orders',
    questions: [
      'What is Sellerboard page for?',
      'How I use sellerboard to manage my orders and requests?',
      'How I use sellerboard to manage my shipments?',
      'How I use sellerboard to manage my invoices?',
      'How I use sellerboard to manage my payments?',
    ],
    qty: 5,
  },
  {
    id: 9,
    title: 'Payments',
    icon: 'material-symbols:payments-outline-rounded',
    questions: [
      'Which bank details are required so I can receive my payments?',
      'What is the payments process life cycle?',
      'How I use sellerboard to manage my Payment Pending?',
      'How I use sellerboard to manage my Payments Disbursal?',
      'How I use sellerboard to manage my Payments Retrieve?',
      'How much will cost me to deiver my shipments?',
      'How much will cost me to return my shipments?',
      'What is Holding payment policy & how it protect me?',
    ],
    qty: 8,
  },
  {
    id: 10,
    title: 'Shipments',
    icon: 'la:shipping-fast',
    questions: [
      'What is Shipping method on SKU Markets?',
      'How I use sellerboard to manage my shipments?',
      'How the promising time works?',
      'How Should I ship my Orders?',
      'Which fulfilment Type is SKU Markets use?',
      'What is direct ship by seller works?',
      'How I use sellerboard to manage my Pending shipments?',
      'How I use sellerboard to ship my shipments?',
      'How I use sellerboard to deliver my shipments?',
      'How I use sellerboard to return shipments?',
    ],
    qty: 10,
  },
  {
    id: 11,
    title: 'Return & Refund',
    icon: 'gridicons:refund',
    questions: [
      'What is Return & Refund Policy?',
      'How I use sellerboard to return shipments?',
      'How much will cost me to return my shipments?',
    ],
    qty: 3,
  },
  {
    id: 12,
    title: 'Problem with the Product',
    icon: 'fluent-mdl2:product-release',
    questions: [
      'I have purchased product and I have issue with it?',
      'What do you recommended me when I do request new stock?',
      'How can I chat with the seller to return my orders?',
      'If I return my orders back to the seller but he refused it?',
    ],
    qty: 4,
  },
  {
    id: 13,
    title: 'Guarantees and Assurances',
    icon: 'iconoir:card-security',
    questions: [
      'What is Holding payment policy & how it protect me?',
      'How do you gurantee SKUs are not fake?',
      'How do you verify Sellers?',
      'How sellers rate are calculated?',
      'How products rate are calculated?',
    ],
    qty: 5,
  },
  {
    id: 14,
    title: 'Sales Channels Management',
    icon: 'icon-park-outline:sales-report',
    questions: [
      'Sales Channels Management',
      'What is SKU Markets Sales Channels page for?',
      'What is SKU Markets Bots Automations page for?',
      'What is SKU Markets Growth page for?',
      'What is SKU Markets Inventory page for?',
      'What is SKU Markets Competitors page for?',
      'How do integrate Ecommerce platforms & shopping carts?',
      'How do integrate Shipping Companies?',
      'How do Bots Automations help me to automate my business cross sales channels?',
    ],
    qty: 8,
  },
  {
    id: 15,
    title: 'Financials',
    icon: 'fluent-mdl2:financial',
    questions: [
      'Which bank details are required so I can receive my payments?',
      'I have issues on tax, invoices and credit notes with my customers?',
      'How will I get paid for my sales?',
      'How can I get my financials reports?',
      'Understanding the SKU Markets fees bills?',
    ],
    qty: 5,
  },
  {
    id: 16,
    title: 'VAT FAQs',
    icon: 'tabler:receipt-tax',
    questions: [
      'Where can I download my tax invoices?',
      'Should I add my VAT and taxes in the prices?',
      'VAT Frequently asked questions',
    ],
    qty: 3,
  },
  {
    id: 17,
    title: 'Advertising and Marketing Solutions',
    icon: 'icon-park-outline:market-analysis',
    questions: [
      'How can I advertise my products on SKU Markets?',
      'What are Product Promotion Ads (PPA)?',
      'What are Category Landing Page Promotion Ads (CLPPA)?',
      'What are Home Landing Page Promotion Ads (HLPPA)?',
      'How to have banners on SKU Markets CLP & HLP?',
    ],
    qty: 5,
  },
  {
    id: 18,
    title: 'Export & Reporting',
    icon: 'material-symbols:export-notes-outline-rounded',
    questions: [
      'How to export my SKUs?',
      'How to export my orders?',
      'How to export my shipments?',
      'How to export my invoices orders?',
      'How to export my Credit Notes?',
      'How to export my Payments Disbursal?',
      'How to export my Outstanding Payments?',
      'How to export my Order Referral fees invoices?',
      'How to export my VAT Payable?',
      'How to export data from tables?',
      'How to print data from tables?',
    ],
    qty: 11,
  },
  {
    id: 19,
    title: 'Import',
    icon: 'fontisto:import',
    questions: [
      'How to activate my SKUs to sell it on SKU Markets?',
      'How to bulk upload up to unlimited SKUs to my portfolio?',
      'How to bulk upload up to unlimited SKUs to my alerts?',
    ],
    qty: 3,
  },
  {
    id: 20,
    title: 'Chat',
    icon: 'ic:baseline-voice-chat',
    questions: [
      'Can I chat with any sellers?',
      'How to use chat?',
      'What is the regulations  and rules for chatting?',
      'How can I chat with the seller from the seller profile page?',
    ],
    qty: 4,
  },
];
