import MPLogo from 'components/common/MPLogo';
import BooleanTag from 'components/common/TableColumns/BooleanTag';
import FulfillmentColumn from 'components/common/TableColumns/FulfillmentColumn';
import LiveColumn from 'components/common/TableColumns/LiveColumn';
import SkuColumn from 'components/common/TableColumns/SkuColumn';
import TagsColumn from 'components/common/TableColumns/TagsColumn';

const columns = [
  {
    field: 'id',
    hide: true,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku',
    headerName: 'SKU',
    align: 'center',
    headerAlign: 'center',
    width: 200,
    sortable: false,
    filterable: false,
    disableColumnMenu: true,
    renderCell: ({ row }) => <SkuColumn row={row} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'marketplace',
    headerName: 'Marketplace',
    align: 'center',
    headerAlign: 'center',
    renderCell: (params) => <MPLogo marketplace={params.row?.sku_marketplace} />,
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'category_en',
    type: 'number',
    headerName: 'Category',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'brand_en',
    type: 'number',
    headerName: 'Brand',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'number_of_sellers',
    type: 'number',
    headerName: 'Stores',
    align: 'center',
    headerAlign: 'center',
    width: 70,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku_rate',
    type: 'number',
    headerName: 'Rate',
    align: 'center',
    headerAlign: 'center',
    width: 70,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sku_rank',
    type: 'number',
    headerName: 'Rank',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'fulfillment',
    renderCell: ({ row }) => <FulfillmentColumn row={row} />,
    type: 'number',
    headerName: 'Fulfillment Type',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'is_live',
    type: 'boolean',
    headerName: 'SKU Status',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
    renderCell: ({ row }) => <LiveColumn row={row} />,
  },
  {
    field: 'current_price',
    type: 'number',
    headerName: 'BuyBox Sale Price',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'price_change',
    type: 'number',
    headerName: 'Chg 24H',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'mxPrice',
    type: 'number',
    headerName: 'Max Offer Price',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    renderCell: ({ row }) => <span>{row?.getTopBottomPrice?.topPrice?.last30Days || 0}</span>,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'minPrice',
    type: 'number',
    headerName: 'Min Offer Price',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    renderCell: ({ row }) => <span>{row?.getTopBottomPrice?.bottomPrice?.last30Days || 0}</span>,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'opp_ff',
    type: 'boolean',
    headerName: 'E Opp To Fulfillment',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    renderCell: ({ value }) => <BooleanTag isTrue={value} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'opp_stock',
    type: 'boolean',
    headerName: 'E Opp To Stock',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    renderCell: ({ value }) => <BooleanTag isTrue={value} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'trade_value',
    type: 'number',
    headerName: 'Trade Volume',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'tags',
    headerName: 'Tags',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    renderCell: ({ row }) => <TagsColumn row={row} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'average_selling_price',
    type: 'number',
    headerName: 'ASP',
    align: 'center',
    headerAlign: 'center',
    width: 60,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'volume_to_market_cap_ratio',
    type: 'number',
    headerName: 'Vol (24h) / MCap',
    align: 'center',
    headerAlign: 'center',
    width: 130,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'estimated_SOH',
    type: 'number',
    headerName: 'Estimated SOH',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'days_on_hand',
    type: 'number',
    headerName: 'DOH',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'est_net_revenue',
    type: 'number',
    headerName: 'ENR',
    align: 'center',
    headerAlign: 'center',
    width: 100,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'max_investment',
    type: 'number',
    headerName: 'Max Investment',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'min_investment',
    type: 'number',
    headerName: 'Min Investment',
    align: 'center',
    headerAlign: 'center',
    width: 120,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'EQTI',
    type: 'number',
    headerName: 'EQTI',
    align: 'center',
    headerAlign: 'center',
    width: 60,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'estimated_margin',
    type: 'number',
    headerName: 'EM',
    align: 'center',
    headerAlign: 'center',
    width: 90,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'sold_24_hours',
    type: 'number',
    headerName: 'Sales volume L 24 H',
    align: 'center',
    headerAlign: 'center',
    width: 170,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'est_market_cap',
    type: 'number',
    headerName: 'E Marketplace cap',
    align: 'center',
    headerAlign: 'center',
    width: 150,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'opp_other_platform',
    type: 'boolean',
    headerName: 'E Opp to Other Platform Fulfillment',
    align: 'center',
    headerAlign: 'center',
    width: 250,
    renderCell: ({ value }) => <BooleanTag isTrue={value} />,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'demand_percentage',
    type: 'number',
    headerName: 'Demand',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    renderCell: ({ row }) => <span>{row?.demand_percentage?.toFixed(2) || 0}%</span>,
    headerClassName: 'super-app-theme--header',
  },
  {
    field: 'supply_percentage',
    type: 'number',
    headerName: 'Supply',
    align: 'center',
    headerAlign: 'center',
    width: 80,
    renderCell: ({ row }) => <span>{row?.supply_percentage?.toFixed(2) || 0}%</span>,
    headerClassName: 'super-app-theme--header',
  },
];

export default columns;
