import MPLogo from 'components/common/MPLogo';

const columns = [
    {
        field: 'id',
        hide: true,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'marketplace',
        headerName: 'Marketplace',
        align: 'center',
        headerAlign: 'center',
        renderCell: ({ row }) => <MPLogo marketplace={row?.id} />,
        width: 120,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'products',
        type: 'number',
        headerName: 'SKUs',
        align: 'center',
        headerAlign: 'center',
        width: 140,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'categories',
        type: 'number',
        headerName: 'Categories',
        align: 'center',
        headerAlign: 'center',
        width: 120,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'brands',
        type: 'number',
        headerName: 'Brands',
        align: 'center',
        headerAlign: 'center',
        width: 90,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'stores',
        type: 'number',
        headerName: 'Stores',
        align: 'center',
        headerAlign: 'center',
        width: 60,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'live',
        type: 'number',
        headerName: 'Live SKUs',
        align: 'center',
        headerAlign: 'center',
        width: 90,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'notLive',
        type: 'number',
        headerName: 'Not Live SKUs',
        align: 'center',
        headerAlign: 'center',
        width: 120,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'ff_store',
        type: 'number',
        headerName: 'Fulfilled by Stores',
        align: 'center',
        headerAlign: 'center',
        width: 140,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'ff_mp',
        type: 'number',
        headerName: 'Fulfilled by MP',
        align: 'center',
        headerAlign: 'center',
        width: 140,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'avg_price',
        type: 'number',
        headerName: 'Average Selling Price',
        align: 'center',
        headerAlign: 'center',
        width: 160,
        headerClassName: 'super-app-theme--header',
    },
    {
        field: 'estimated_SOH',
        type: 'number',
        headerName: 'Estimated Stock On Hand',
        align: 'center',
        headerAlign: 'center',
        width: 200,
        renderCell: ({ value }) => Math.ceil(value || 0),
        headerClassName: 'super-app-theme--header',
    },
];

export default columns;
